# Generated by Django 4.2.19 on 2025-04-10 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('absensi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absen',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absensi', to='accounts.employee'),
        ),
    ]
