# Generated by Django 4.2.19 on 2025-04-10 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absensi', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='absen',
            old_name='employee_id',
            new_name='employee_uuid',
        ),
    ]
